### ISSUE TITLE
Doordeck calls initDoordeck when the app is in the background

### ISSUE THREAD

**Issue by AngeloMateus** [doordeck/doordeck-sdk-react-native#14]
Android devices and now newer IOS devices can open apps when the device approaches NFC tags.

In our case we are calling doordeckSdk.initDoordeck(authToken, darkMode, closeButton) after the user logs in. On android, once the device triggers the NFC tag a dropdown should be displayed showing all the apps that support NFC, however the Doordeck SDK seems to skip this altogether, opens our app and displays the following screen:

![28057F09-342E-4394-BB2E-00F7E4EB7F4E](https://user-images.githubusercontent.com/34476066/112872892-ce08d680-90b8-11eb-8cff-4735ff4b1c01.jpg)

We see this from adb logcat before the screen appears:
03-29 18:07:11.551  3836  6081 E WindowManager: win=Window{21e0b98 u0 com.*****/com.doordeck.sdk.ui.unlock.UnlockActivity} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.WindowManagerService.tryStartExitingAnimation:2798 com.android.server.wm.WindowManagerService.relayoutWindow:2496 com.android.server.wm.Session.relayoutForTranslate:302 android.view.IWindowSession$Stub.onTransact:518 com.android.server.wm.Session.onTransact:186 android.os.Binder.execTransact:739 <bottom of call stack>

Once this screen is dismissed the app is closed.

This is interfering with some of our other NFC functionalities which worked prior to adding this SDK.
Is there anything we should be doing, or is there a way to disable the modal from being run by SDK automatically?

**Comment by marwan87** [comment]
Hi @AngeloMateus 
The SDK does not support background NFC reading.  You would need to build this journey your self.  

The only reason it would skip the nfc choice this is if you had picked previously. 

Please contact me on marwan@doordeck.com and I can try to assist you further.
